[build]
builder = "nixpacks"
buildCommand = "npx nx run prisma:generate-types && npx nx run backend:build:production"
watchPatterns = ["/backend"]

[deploy]
startCommand = "npx nx run prisma:migrate-deploy && npx nx run backend:serve:production"

# Remember thay tou need to have endpoints deployed before start using below healthchecks
#healthcheckPath = "/api/health"
#healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"